# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Autostart Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
#first set volume to 70% to avoid loud boot sound
exec-once = pactl set-sink-volume @DEFAULT_SINK@ 70%
exec-once = mpv /home/vardhin/.config/hypr/sounds/boot.wav
#then revert the volume back to the previous level
exec-once = pactl set-sink-volume @DEFAULT_SINK@ 100%

source = ~/.config/hypr/config/defaults.conf

# Autostart wiki https://wiki.hyprland.org/0.45.0/Configuring/Keywords/#executing #
exec-once = swww-daemon
exec-once = ags run & # AGS v3 — bar, notifications, OSD, launcher, session
exec-once = fcitx5 -d &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

exec-once = wl-paste --watch cliphist store
exec-once = wl-clip-persist --clipboard regular

# ## Slow app launch fix
exec-once = systemctl --user import-environment &
exec-once = hash dbus-update-activation-environment 2>/dev/null &
exec-once = dbus-update-activation-environment --systemd &

# ## Idle configuration
exec-once = $idlehandler