# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Colors Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

#source = ~/.cache/wal/colors-hyprland.conf

$cachylgreen = rgba(82dcccff)
$cachymgreen = rgba(00aa84ff)
$cachydgreen = rgba(007d6fff)
$cachylblue = rgba(01ccffff)
$cachymblue = rgba(182545ff)
$cachydblue = rgba(111826ff)
$cachywhite = rgba(ffffffff)
$cachygrey = rgba(ddddddff)
$cachygray = rgba(798bb2ff)

# Add these lines to define standard colors
$color0  = rgba(1d2021ff)
$color1  = rgba(cc241dff)
$color2  = rgba(98971aff)
$color3  = rgba(d79921ff)
$color4  = rgba(458588ff)
$color5  = rgba(b16286ff)
$color6  = rgba(689d6aff)
$color7  = rgba(a89984ff)
$color8  = rgba(928374ff)
$color9  = rgba(fb4934ff)
$color10 = rgba(b8bb26ff)
$color11 = rgba(fabd2fff)
$color12 = rgba(83a598ff)
$color13 = rgba(d3869bff)
$color14 = rgba(8ec07cff)
$color15 = rgba(ebdbb2ff)

$foreground = rgba(ebdbb2ff)
