# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$TERMINAL = kitty
$EDITOR = $TERMINAL -e nano
$BROWSER = firefox
$mainMod = SUPER
$scrPath = $HOME/scripts
$idlehandler = hypridle
$scriptPath = $HOME/.config/hypr/scripts