# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$TERMINAL = kitty
$EDITOR = $TERMINAL -e nano
$FILE_MANAGER = dolphin
$BROWSER = firefox
$MENU = wofi
$mainMod = SUPER
$scrPath = $HOME/.local/bin
$idlehandler = hypridle
$scriptPath = $HOME/.config/hypr/scripts