# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

env = XCURSOR_THEME,Bibata-Modern-Amber

envd = HYPRCURSOR_SIZE,24
envd = XCURSOR_SIZE,24
envd = QT_CURSOR_SIZE,24

env = PATH,$HOME/.local/bin:$PATH

env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt5ct

env = XDG_SESSION_TYPE,wayland
env = GDK_BACKEND,wayland
env = CLUTTER_BACKEND,wayland
env = SDL_VIDEODRIVER,wayland

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

env = TERMINAL,kitty
env = TERM,kitty

env = AWWW_TRANSITION,wipe
env = AWWW_TRANSITION_STEP, 90
env = AWWW_TRANSITION_FPS, 60
env = AWWW_TRANSITION_ANGLE, 30

# AGS (Aylur's GTK Shell) environment
env = AGS_SKIP_V_CHECK, true
