# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

input {
    follow_mouse = 1 # 0|1|2|3
    float_switch_override_focus = 2

    kb_options = fkeys:basic_13-24
    #kb_options = caps:swapescape

    touchpad {
        natural_scroll = false
    }
}
