# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

monitor = , preferred, auto, 1.2

# Adjust GDK_SCALE accordingly to your liking.
xwayland {
  force_zero_scaling = true       # Unscale XWayland
}

env = GDK_SCALE, 1.25                   # GDK Scaling Factor
